"""add action history

Revision ID: 072fc4f7ffc2
Revises: fcae7fcaecca
Create Date: 2026-03-29 17:34:44.026641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072fc4f7ffc2'
down_revision = 'fcae7fcaecca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('action_text', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.create_index('ix_action_store_text', ['store_id', 'action_text'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.drop_index('ix_action_store_text')

    op.drop_table('action_history')
    # ### end Alembic commands ###
