"""add archive + delete tracking to stores

Revision ID: 1819488dcf06
Revises: b06bd82ccd3e
Create Date: 2026-02-15 19:28:58.639393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1819488dcf06'
down_revision = 'b06bd82ccd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
