"""empty message

Revision ID: 34ed7dfea464
Revises: 8f55b729389d
Create Date: 2025-11-14 11:02:43.256698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ed7dfea464'
down_revision = '8f55b729389d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('store_name_placeholder', sa.String(length=100), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_ticket_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_ticket_token'))

    op.drop_table('onboarding_ticket')
    # ### end Alembic commands ###
