"""Create managed stores

Revision ID: 352701be42c2
Revises: ce6ed3cc1e8a
Create Date: 2026-08-01 11:25:51.658861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352701be42c2'
down_revision = 'ce6ed3cc1e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_stores',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('store_code', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('dealer_code', sa.String(length=40), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('provisioning', 'active', 'inactive', 'closed', 'retired', name='managed_store_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('state_province_code', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('primary_brand', sa.String(length=80), nullable=True),
    sa.Column('brands', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('managed_store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_managed_stores_effective_period_valid')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_managed_stores_name_required')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_managed_stores_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('managed_store_id', name=op.f('pk_managed_stores')),
    sa.UniqueConstraint('enterprise_id', 'dealer_code', name='uq_managed_stores_enterprise_dealer_code'),
    sa.UniqueConstraint('enterprise_id', 'external_reference', name='uq_managed_stores_enterprise_external_reference'),
    sa.UniqueConstraint('enterprise_id', 'managed_store_id', name='uq_managed_stores_tenant_identity'),
    sa.UniqueConstraint('enterprise_id', 'slug', name='uq_managed_stores_enterprise_slug'),
    sa.UniqueConstraint('enterprise_id', 'store_code', name='uq_managed_stores_enterprise_store_code')
    )
    with op.batch_alter_table('managed_stores', schema=None) as batch_op:
        batch_op.create_index('ix_managed_stores_enterprise_brand', ['enterprise_id', 'primary_brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_stores_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_managed_stores_enterprise_status', ['enterprise_id', 'status'], unique=False)

    op.create_table('managed_store_group_memberships',
    sa.Column('managed_store_id', sa.Uuid(), nullable=False),
    sa.Column('organizational_group_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('managed_store_group_membership_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_managed_store_group_memberships_effective_period_valid')),
    sa.ForeignKeyConstraint(['enterprise_id', 'managed_store_id'], ['managed_stores.enterprise_id', 'managed_stores.managed_store_id'], name='fk_managed_store_group_memberships_managed_store', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'organizational_group_id'], ['organizational_groups.enterprise_id', 'organizational_groups.organizational_group_id'], name='fk_managed_store_group_memberships_organizational_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_managed_store_group_memberships_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('managed_store_group_membership_id', name=op.f('pk_managed_store_group_memberships')),
    sa.UniqueConstraint('enterprise_id', 'managed_store_id', 'organizational_group_id', 'effective_from', name='uq_managed_store_group_memberships_effective_membership')
    )
    with op.batch_alter_table('managed_store_group_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_store_group_memberships_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_managed_store_group_memberships_group', ['enterprise_id', 'organizational_group_id'], unique=False)
        batch_op.create_index('ix_managed_store_group_memberships_store', ['enterprise_id', 'managed_store_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('managed_store_group_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_managed_store_group_memberships_store')
        batch_op.drop_index('ix_managed_store_group_memberships_group')
        batch_op.drop_index(batch_op.f('ix_managed_store_group_memberships_enterprise_id'))

    op.drop_table('managed_store_group_memberships')
    with op.batch_alter_table('managed_stores', schema=None) as batch_op:
        batch_op.drop_index('ix_managed_stores_enterprise_status')
        batch_op.drop_index(batch_op.f('ix_managed_stores_enterprise_id'))
        batch_op.drop_index('ix_managed_stores_enterprise_brand')

    op.drop_table('managed_stores')
    # ### end Alembic commands ###
