"""Create employees

Revision ID: 372abb8f0ee5
Revises: 6d46b50500aa
Create Date: 2026-08-01 11:50:30.813383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372abb8f0ee5'
down_revision = '6d46b50500aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_number', sa.String(length=40), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('preferred_name', sa.String(length=80), nullable=True),
    sa.Column('work_email', sa.String(length=160), nullable=True),
    sa.Column('mobile_phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'leave', 'terminated', 'retired', name='employee_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(trim(first_name)) > 0', name=op.f('ck_employees_first_name_required')),
    sa.CheckConstraint('length(trim(last_name)) > 0', name=op.f('ck_employees_last_name_required')),
    sa.CheckConstraint('termination_date IS NULL OR hire_date IS NULL OR termination_date >= hire_date', name=op.f('ck_employees_termination_not_before_hire')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_employees_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('pk_employees')),
    sa.UniqueConstraint('enterprise_id', 'employee_id', name='uq_employees_tenant_identity'),
    sa.UniqueConstraint('enterprise_id', 'employee_number', name='uq_employees_enterprise_employee_number'),
    sa.UniqueConstraint('enterprise_id', 'external_reference', name='uq_employees_enterprise_external_reference'),
    sa.UniqueConstraint('enterprise_id', 'work_email', name='uq_employees_enterprise_work_email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_employees_enterprise_name', ['enterprise_id', 'last_name', 'first_name'], unique=False)
        batch_op.create_index('ix_employees_enterprise_status', ['enterprise_id', 'status'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_enterprise_status')
        batch_op.drop_index('ix_employees_enterprise_name')
        batch_op.drop_index(batch_op.f('ix_employees_enterprise_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
