"""add daily metrics

Revision ID: 3a9a84345fcf
Revises: ea3fb583ddf7
Create Date: 2026-04-05 16:34:17.691042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9a84345fcf'
down_revision = 'ea3fb583ddf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mtd_gross', sa.Float(), nullable=True),
    sa.Column('yesterday_gross', sa.Float(), nullable=True),
    sa.Column('today_appts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', name='uq_metrics_store_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
