"""add cp_ros_mtd to daily_metrics

Revision ID: 3c0ba172b4a0
Revises: 4b7c9248ecaa
Create Date: 2026-05-11 09:38:41.876898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0ba172b4a0'
down_revision = '4b7c9248ecaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp_ros_mtd', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_column('cp_ros_mtd')

    # ### end Alembic commands ###
