"""Create positions

Revision ID: 42c60d2e3cf2
Revises: 372abb8f0ee5
Create Date: 2026-08-01 11:56:46.945782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c60d2e3cf2'
down_revision = '372abb8f0ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'frozen', 'eliminated', 'retired', name='position_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('is_managerial', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('budgeted_fte', sa.Numeric(precision=5, scale=2), server_default='1.00', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('budgeted_fte > 0', name=op.f('ck_positions_budgeted_fte_positive')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_positions_effective_period_valid')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_positions_title_required')),
    sa.ForeignKeyConstraint(['enterprise_id', 'department_id'], ['departments.enterprise_id', 'departments.department_id'], name='fk_positions_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_positions_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('position_id', name=op.f('pk_positions')),
    sa.UniqueConstraint('enterprise_id', 'department_id', 'code', name='uq_positions_department_code'),
    sa.UniqueConstraint('enterprise_id', 'position_id', name='uq_positions_tenant_identity')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_department_status', ['enterprise_id', 'department_id', 'status'], unique=False)
        batch_op.create_index('ix_positions_department_title', ['enterprise_id', 'department_id', 'title'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_enterprise_id'), ['enterprise_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_enterprise_id'))
        batch_op.drop_index('ix_positions_department_title')
        batch_op.drop_index('ix_positions_department_status')

    op.drop_table('positions')
    # ### end Alembic commands ###
