"""workday fix for days in month

Revision ID: 4b7c9248ecaa
Revises: 6c002e6b8368
Create Date: 2026-04-27 21:40:05.717219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7c9248ecaa'
down_revision = '6c002e6b8368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_forecast', schema=None) as batch_op:
        batch_op.drop_column('work_days')

    # ### end Alembic commands ###
