"""add decision weights

Revision ID: 4c4b809e2b3b
Revises: 4df82f969f20
Create Date: 2026-03-29 18:42:13.933698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4b809e2b3b'
down_revision = '4df82f969f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('base_weight', sa.Float(), nullable=False),
    sa.Column('history_weight', sa.Float(), nullable=False),
    sa.Column('context_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_weights')
    # ### end Alembic commands ###
