"""add action context

Revision ID: 4df82f969f20
Revises: 072fc4f7ffc2
Create Date: 2026-03-29 17:50:08.203074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df82f969f20'
down_revision = '072fc4f7ffc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatch_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspection_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('service_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.drop_column('service_count')
        batch_op.drop_column('approval_count')
        batch_op.drop_column('inspection_count')
        batch_op.drop_column('dispatch_count')

    # ### end Alembic commands ###
