"""Create capabilities

Revision ID: 4f6ffabb9d08
Revises: d05035d48cf1
Create Date: 2026-08-02 09:08:51.342448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6ffabb9d08'
down_revision = 'd05035d48cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'retired', name='capability_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_capabilities_effective_period_valid')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_capabilities_name_required')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_capabilities_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('pk_capabilities')),
    sa.UniqueConstraint('enterprise_id', 'capability_id', name='uq_capabilities_tenant_identity'),
    sa.UniqueConstraint('enterprise_id', 'key', name='uq_capabilities_enterprise_key')
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index('ix_capabilities_enterprise_category', ['enterprise_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_capabilities_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_capabilities_enterprise_name', ['enterprise_id', 'name'], unique=False)
        batch_op.create_index('ix_capabilities_enterprise_status', ['enterprise_id', 'status'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index('ix_capabilities_enterprise_status')
        batch_op.drop_index('ix_capabilities_enterprise_name')
        batch_op.drop_index(batch_op.f('ix_capabilities_enterprise_id'))
        batch_op.drop_index('ix_capabilities_enterprise_category')

    op.drop_table('capabilities')
    # ### end Alembic commands ###
