"""Create Enterprise table

Revision ID: 52c97fb4ecad
Revises: 3c0ba172b4a0
Create Date: 2026-07-25 21:57:27.383051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c97fb4ecad'
down_revision = '3c0ba172b4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('enterprise_code', sa.String(length=10), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('provisioning', 'active', 'suspended', 'retired', name='enterprise_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_enterprises_name_required')),
    sa.CheckConstraint('retired_at IS NULL OR retired_at >= activated_at', name=op.f('ck_enterprises_retirement_after_activation')),
    sa.PrimaryKeyConstraint('enterprise_id', name=op.f('pk_enterprises')),
    sa.UniqueConstraint('enterprise_code', name=op.f('uq_enterprises_enterprise_code')),
    sa.UniqueConstraint('external_reference', name=op.f('uq_enterprises_external_reference')),
    sa.UniqueConstraint('slug', name=op.f('uq_enterprises_slug'))
    )
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.create_index('ix_enterprises_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.drop_index('ix_enterprises_status')

    op.drop_table('enterprises')
    # ### end Alembic commands ###
