"""Update WorkLog for CDK format

Revision ID: 64958730babe
Revises: 77d6b9ba84cb
Create Date: 2025-11-14 13:13:30.618224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64958730babe'
down_revision = '77d6b9ba84cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_time', sa.Float(), nullable=True))
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))
        batch_op.drop_column('actual_time')

    # ### end Alembic commands ###
