"""sync labor_grid to model

Revision ID: 64f6c0a9d1ab
Revises: e15234e7efd9
Create Date: 2026-02-15 23:20:15.405136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f6c0a9d1ab'
down_revision = 'e15234e7efd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asm', schema=None) as batch_op:
        batch_op.create_index('ix_asm_store_id', ['store_id'], unique=False)
        batch_op.create_unique_constraint('uq_asm_store_number', ['store_id', 'asm_number'])
        batch_op.create_foreign_key('fk_asm_store', 'managed_store', ['store_id'], ['id'])

    with op.batch_alter_table('financial_forecast', schema=None) as batch_op:
        batch_op.create_index('ix_forecast_store_id', ['store_id'], unique=False)
        batch_op.create_foreign_key('fk_forecast_store', 'managed_store', ['store_id'], ['id'])

    #with op.batch_alter_table('labor_grid', schema=None) as batch_op:
    #   pass


    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('ix_ro_store_id', ['store_id'], unique=False)
        batch_op.create_unique_constraint('uq_ro_store_number', ['store_id', 'ro_number'])
        batch_op.create_foreign_key('fk_repair_order_store', 'managed_store', ['store_id'], ['id'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_role_store', 'managed_store', ['store_id'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_store', 'managed_store', ['store_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_index('ix_user_store_id', ['store_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_store_username', ['store_id', 'username'])
        batch_op.create_foreign_key('fk_user_store', 'managed_store', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_store_username', type_='unique')
        batch_op.drop_index('ix_user_store_id')
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_ro_store_number', type_='unique')
        batch_op.drop_index('ix_ro_store_id')
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    #with op.batch_alter_table('labor_grid', schema=None) as batch_op:
    #    pass


    with op.batch_alter_table('financial_forecast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_forecast_store_id')

    with op.batch_alter_table('asm', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_asm_store_number', type_='unique')
        batch_op.drop_index('ix_asm_store_id')

    # ### end Alembic commands ###
