"""fresh clean schema

Revision ID: 6c002e6b8368
Revises: 
Create Date: 2026-04-19 19:06:20.747891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c002e6b8368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=True),
    sa.Column('labor_gross', sa.Float(), nullable=True),
    sa.Column('parts_gross', sa.Float(), nullable=True),
    sa.Column('sublet_gross', sa.Float(), nullable=True),
    sa.Column('today_appts', sa.Integer(), nullable=True),
    sa.Column('appt_7_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('month_day', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_day'),
    sa.UniqueConstraint('name')
    )
    op.create_table('managed_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=20), server_default='beta', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('admin_username', sa.String(length=120), nullable=False),
    sa.Column('admin_password_enc', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('routesheet_audit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('tech_hours_audit_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('store_name_placeholder', sa.String(length=100), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_ticket_token'), ['token'], unique=True)

    op.create_table('operator_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_user_username'), ['username'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('admin_username', sa.String(length=80), nullable=False),
    sa.Column('admin_password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('action_text', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('dispatch_count', sa.Integer(), nullable=True),
    sa.Column('inspection_count', sa.Integer(), nullable=True),
    sa.Column('approval_count', sa.Integer(), nullable=True),
    sa.Column('service_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], name='fk_actionhistory_store'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.create_index('ix_action_store_text', ['store_id', 'action_text'], unique=False)
        batch_op.create_index('ix_action_store_time', ['store_id', 'timestamp'], unique=False)

    op.create_table('decision_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('base_weight', sa.Float(), nullable=False),
    sa.Column('history_weight', sa.Float(), nullable=False),
    sa.Column('context_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], name='fk_weights_store'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    with op.batch_alter_table('decision_weights', schema=None) as batch_op:
        batch_op.create_index('ix_weights_store_id', ['store_id'], unique=False)

    op.create_table('financial_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('labor_gross', sa.Float(), nullable=True),
    sa.Column('parts_gross', sa.Float(), nullable=True),
    sa.Column('other_gross', sa.Float(), nullable=True),
    sa.Column('total_gross', sa.Float(), nullable=True),
    sa.Column('expected_frh', sa.Float(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_forecast', schema=None) as batch_op:
        batch_op.create_index('ix_forecast_store_id', ['store_id'], unique=False)

    op.create_table('labor_grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starting_rate', sa.Float(), nullable=True),
    sa.Column('peak_hours', sa.Float(), nullable=True),
    sa.Column('escalator_percent', sa.Float(), nullable=True),
    sa.Column('return_normal_hours', sa.Float(), nullable=True),
    sa.Column('discount_start_hours', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_laborgrid_store_name')
    )
    with op.batch_alter_table('labor_grid', schema=None) as batch_op:
        batch_op.create_index('ix_laborgrid_store_id', ['store_id'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_role_store_name')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('ix_role_store_id', ['store_id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_team_store_name')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index('ix_team_store_id', ['store_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'username', name='uq_user_store_username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_store_id', ['store_id'], unique=False)

    op.create_table('asm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asm_number', sa.String(length=20), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'asm_number', name='uq_asm_store_number')
    )
    with op.batch_alter_table('asm', schema=None) as batch_op:
        batch_op.create_index('ix_asm_store_id', ['store_id'], unique=False)

    op.create_table('financial_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_labor_rate', sa.Float(), nullable=True),
    sa.Column('parts_to_labor_ratio', sa.Float(), nullable=True),
    sa.Column('labor_margin', sa.Float(), nullable=True),
    sa.Column('parts_margin', sa.Float(), nullable=True),
    sa.Column('cp_effective_labor_rate', sa.Float(), nullable=True),
    sa.Column('cp_parts_to_labor_ratio', sa.Float(), nullable=True),
    sa.Column('cp_labor_margin', sa.Float(), nullable=True),
    sa.Column('cp_parts_margin', sa.Float(), nullable=True),
    sa.Column('other_ro_gross', sa.Float(), nullable=True),
    sa.Column('unapplied_time_cost', sa.Float(), nullable=True),
    sa.Column('parts_retail_gross', sa.Float(), nullable=True),
    sa.Column('wholesale_gross', sa.Float(), nullable=True),
    sa.Column('parts_inventory_adjust', sa.Float(), nullable=True),
    sa.Column('parts_allowance', sa.Float(), nullable=True),
    sa.Column('purchase_discounts', sa.Float(), nullable=True),
    sa.Column('parts_fill_rate', sa.Float(), nullable=True),
    sa.Column('parts_turn_rate', sa.Float(), nullable=True),
    sa.Column('bays_with_lifts', sa.Integer(), nullable=True),
    sa.Column('bays_without_lifts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('labor_grid_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('effective_rate', sa.Float(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['labor_grid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_capabilities',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'capability_id')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tech_number', sa.String(length=20), nullable=True),
    sa.Column('tech_level', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('daily_production_objective', sa.Float(), nullable=True),
    sa.Column('dpo_calculation_mode', sa.String(length=20), nullable=True),
    sa.Column('hist_frh_total', sa.Float(), nullable=True),
    sa.Column('hist_days_in_period', sa.Integer(), nullable=True),
    sa.Column('hist_training_days', sa.Integer(), nullable=True),
    sa.Column('hist_vacation_days', sa.Integer(), nullable=True),
    sa.Column('expected_lift_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('production_objective_memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('previous_objective', sa.Float(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ro_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_info', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('promised_time', sa.DateTime(), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_read', sa.Boolean(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=True),
    sa.Column('asm_id', sa.Integer(), nullable=True),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('audited', sa.Boolean(), nullable=True),
    sa.Column('audit_source', sa.String(length=50), nullable=True),
    sa.Column('audit_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['asm_id'], ['asm.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['managed_store.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ro_number', name='uq_ro_store_number')
    )
    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.create_index('ix_ro_store_id', ['store_id'], unique=False)

    op.create_table('schedule_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('actual_time', sa.Float(), nullable=True),
    sa.Column('ro_number', sa.String(length=50), nullable=True),
    sa.Column('line_item', sa.String(length=10), nullable=True),
    sa.Column('flat_rate_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_log')
    op.drop_table('schedule_entry')
    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.drop_index('ix_ro_store_id')

    op.drop_table('repair_order')
    op.drop_table('production_objective_memo')
    op.drop_table('user_roles')
    op.drop_table('team_schedule')
    op.drop_table('team_member')
    op.drop_table('role_capabilities')
    op.drop_table('labor_grid_rate')
    op.drop_table('financial_inputs')
    with op.batch_alter_table('asm', schema=None) as batch_op:
        batch_op.drop_index('ix_asm_store_id')

    op.drop_table('asm')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_store_id')

    op.drop_table('user')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('ix_team_store_id')

    op.drop_table('team')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('ix_role_store_id')

    op.drop_table('role')
    with op.batch_alter_table('labor_grid', schema=None) as batch_op:
        batch_op.drop_index('ix_laborgrid_store_id')

    op.drop_table('labor_grid')
    with op.batch_alter_table('financial_forecast', schema=None) as batch_op:
        batch_op.drop_index('ix_forecast_store_id')

    op.drop_table('financial_forecast')
    with op.batch_alter_table('decision_weights', schema=None) as batch_op:
        batch_op.drop_index('ix_weights_store_id')

    op.drop_table('decision_weights')
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.drop_index('ix_action_store_time')
        batch_op.drop_index('ix_action_store_text')

    op.drop_table('action_history')
    op.drop_table('stores')
    with op.batch_alter_table('operator_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_user_username'))

    op.drop_table('operator_user')
    with op.batch_alter_table('onboarding_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_ticket_token'))

    op.drop_table('onboarding_ticket')
    op.drop_table('managed_store')
    op.drop_table('holiday')
    op.drop_table('daily_metrics')
    op.drop_table('capability')
    # ### end Alembic commands ###
