"""Create departments

Revision ID: 6d46b50500aa
Revises: 352701be42c2
Create Date: 2026-08-01 11:40:01.264183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d46b50500aa'
down_revision = '352701be42c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('managed_store_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('department_type', sa.Enum('service', 'parts', 'sales', 'finance', 'collision', 'reconditioning', 'administration', 'other', name='department_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'closed', 'retired', name='department_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_departments_effective_period_valid')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_departments_name_required')),
    sa.ForeignKeyConstraint(['enterprise_id', 'managed_store_id'], ['managed_stores.enterprise_id', 'managed_stores.managed_store_id'], name='fk_departments_managed_store', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_departments_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_departments')),
    sa.UniqueConstraint('enterprise_id', 'department_id', name='uq_departments_tenant_identity'),
    sa.UniqueConstraint('enterprise_id', 'managed_store_id', 'code', name='uq_departments_store_code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_departments_store_status', ['enterprise_id', 'managed_store_id', 'status'], unique=False)
        batch_op.create_index('ix_departments_store_type', ['enterprise_id', 'managed_store_id', 'department_type'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('ix_departments_store_type')
        batch_op.drop_index('ix_departments_store_status')
        batch_op.drop_index(batch_op.f('ix_departments_enterprise_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###
