"""Create MI v5 teams

Revision ID: 76dc5e635e0a
Revises: f93414eca218
Create Date: 2026-08-02 09:42:24.197889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dc5e635e0a'
down_revision = 'f93414eca218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_v5',
    sa.Column('organizational_group_id', sa.Uuid(), nullable=True),
    sa.Column('managed_store_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('leader_employee_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('team_type', sa.Enum('leadership', 'operations', 'service', 'parts', 'sales', 'technician', 'project', 'executive', 'cross_functional', 'custom', name='team_type', native_enum=False), server_default='operations', nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'completed', 'retired', name='team_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_teams_v5_effective_period_valid')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_teams_v5_name_required')),
    sa.CheckConstraint(
    """
    (
        CASE WHEN organizational_group_id IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN managed_store_id IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN department_id IS NOT NULL THEN 1 ELSE 0 END
    ) <= 1
    """,
    name=op.f("ck_teams_v5_single_organizational_anchor"),
    ),
    sa.ForeignKeyConstraint(['enterprise_id', 'department_id'], ['departments.enterprise_id', 'departments.department_id'], name='fk_teams_v5_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'leader_employee_id'], ['employees.enterprise_id', 'employees.employee_id'], name='fk_teams_v5_leader_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'managed_store_id'], ['managed_stores.enterprise_id', 'managed_stores.managed_store_id'], name='fk_teams_v5_managed_store', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'organizational_group_id'], ['organizational_groups.enterprise_id', 'organizational_groups.organizational_group_id'], name='fk_teams_v5_organizational_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_teams_v5_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_teams_v5')),
    sa.UniqueConstraint('enterprise_id', 'code', name='uq_teams_v5_enterprise_code'),
    sa.UniqueConstraint('enterprise_id', 'team_id', name='uq_teams_v5_tenant_identity')
    )
    with op.batch_alter_table('teams_v5', schema=None) as batch_op:
        batch_op.create_index('ix_teams_v5_department', ['enterprise_id', 'department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_v5_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_teams_v5_enterprise_status', ['enterprise_id', 'status'], unique=False)
        batch_op.create_index('ix_teams_v5_enterprise_type', ['enterprise_id', 'team_type'], unique=False)
        batch_op.create_index('ix_teams_v5_leader', ['enterprise_id', 'leader_employee_id'], unique=False)
        batch_op.create_index('ix_teams_v5_managed_store', ['enterprise_id', 'managed_store_id'], unique=False)
        batch_op.create_index('ix_teams_v5_organizational_group', ['enterprise_id', 'organizational_group_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('teams_v5', schema=None) as batch_op:
        batch_op.drop_index('ix_teams_v5_organizational_group')
        batch_op.drop_index('ix_teams_v5_managed_store')
        batch_op.drop_index('ix_teams_v5_leader')
        batch_op.drop_index('ix_teams_v5_enterprise_type')
        batch_op.drop_index('ix_teams_v5_enterprise_status')
        batch_op.drop_index(batch_op.f('ix_teams_v5_enterprise_id'))
        batch_op.drop_index('ix_teams_v5_department')

    op.drop_table('teams_v5')
    # ### end Alembic commands ###
