"""Add new financial and capacity fields

Revision ID: 77d6b9ba84cb
Revises: 34ed7dfea464
Create Date: 2025-11-14 11:53:36.165303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d6b9ba84cb'
down_revision = '34ed7dfea464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_inputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp_effective_labor_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cp_parts_to_labor_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cp_labor_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cp_parts_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parts_fill_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parts_turn_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bays_with_lifts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bays_without_lifts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_inputs', schema=None) as batch_op:
        batch_op.drop_column('bays_without_lifts')
        batch_op.drop_column('bays_with_lifts')
        batch_op.drop_column('parts_turn_rate')
        batch_op.drop_column('parts_fill_rate')
        batch_op.drop_column('cp_parts_margin')
        batch_op.drop_column('cp_labor_margin')
        batch_op.drop_column('cp_parts_to_labor_ratio')
        batch_op.drop_column('cp_effective_labor_rate')

    # ### end Alembic commands ###
