"""Added 7 day appts

Revision ID: 85b2563fe2ed
Revises: 3a9a84345fcf
Create Date: 2026-04-10 10:11:48.114712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b2563fe2ed'
down_revision = '3a9a84345fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appt_7_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_column('appt_7_day')

    # ### end Alembic commands ###
