"""Create MI v5 team memberships

Revision ID: 881160180f24
Revises: 76dc5e635e0a
Create Date: 2026-08-02 10:04:48.155081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881160180f24'
down_revision = '76dc5e635e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_memberships_v5',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('membership_type', sa.Enum('member', 'leader', 'coordinator', 'contributor', 'advisor', 'observer', name='team_membership_type', native_enum=False), server_default='member', nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', 'completed', 'cancelled', name='team_membership_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('team_membership_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_team_memberships_v5_effective_period_valid')),
    sa.ForeignKeyConstraint(['enterprise_id', 'employee_id'], ['employees.enterprise_id', 'employees.employee_id'], name='fk_team_memberships_v5_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'team_id'], ['teams_v5.enterprise_id', 'teams_v5.team_id'], name='fk_team_memberships_v5_team', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_team_memberships_v5_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('team_membership_id', name=op.f('pk_team_memberships_v5')),
    sa.UniqueConstraint('enterprise_id', 'team_id', 'employee_id', 'effective_from', name='uq_team_memberships_v5_effective_membership'),
    sa.UniqueConstraint('enterprise_id', 'team_membership_id', name='uq_team_memberships_v5_tenant_identity')
    )
    with op.batch_alter_table('team_memberships_v5', schema=None) as batch_op:
        batch_op.create_index('ix_team_memberships_v5_employee', ['enterprise_id', 'employee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_v5_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_team_memberships_v5_team', ['enterprise_id', 'team_id', 'status'], unique=False)
        batch_op.create_index('uq_team_memberships_v5_current_primary', ['enterprise_id', 'employee_id'], unique=True, sqlite_where=sa.text("is_primary = 1 AND effective_to IS NULL AND status IN ('pending', 'active')"), postgresql_where=sa.text("is_primary = true AND effective_to IS NULL AND status IN ('pending', 'active')"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('team_memberships_v5', schema=None) as batch_op:
        batch_op.drop_index('uq_team_memberships_v5_current_primary', sqlite_where=sa.text("is_primary = 1 AND effective_to IS NULL AND status IN ('pending', 'active')"), postgresql_where=sa.text("is_primary = true AND effective_to IS NULL AND status IN ('pending', 'active')"))
        batch_op.drop_index('ix_team_memberships_v5_team')
        batch_op.drop_index(batch_op.f('ix_team_memberships_v5_enterprise_id'))
        batch_op.drop_index('ix_team_memberships_v5_employee')

    op.drop_table('team_memberships_v5')
    # ### end Alembic commands ###
