"""expand service_description to Text

Revision ID: 8d80f5b4b871
Revises: 0d8bdc753e5d
Create Date: 2026-02-16 01:36:04.041221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d80f5b4b871'
down_revision = '0d8bdc753e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.alter_column('service_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.alter_column('service_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
