"""empty message

Revision ID: 8eb8d4f1019d
Revises: e911fa0caf85
Create Date: 2026-02-15 21:17:43.774392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eb8d4f1019d'
down_revision = 'e911fa0caf85'
branch_labels = None
depends_on = None


def upgrade():
    # ---- managed_store updates ----
    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_password_enc', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_operator_id', sa.Integer(), nullable=True))

        batch_op.alter_column(
            'environment',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=16),
            existing_nullable=False
        )

        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=16),
            existing_nullable=False
        )

    # ✅ STEP 1: Backfill tier values BEFORE enforcing NOT NULL
    op.execute("UPDATE managed_store SET tier = 'beta' WHERE tier IS NULL")

    # ✅ STEP 2: Now enforce NOT NULL
    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.alter_column(
            'tier',
            existing_type=sa.VARCHAR(length=20),
            nullable=False
        )

        batch_op.drop_column('admin_password_encrypted')

    # ---- role constraint updates ----
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name_store'), type_='unique')
        batch_op.create_index('ix_role_store_id', ['store_id'], unique=False)
        batch_op.create_unique_constraint('uq_role_store_name', ['store_id', 'name'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_store_name', type_='unique')
        batch_op.drop_index('ix_role_store_id')
        batch_op.create_unique_constraint(batch_op.f('uq_role_name_store'), ['name', 'store_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_password_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('environment',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('deleted_by_operator_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('admin_password_enc')

    # ### end Alembic commands ###
