"""Add ASM model and fields

Revision ID: 8f55b729389d
Revises: b07144688fb6
Create Date: 2025-11-13 15:19:02.517593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f55b729389d'
down_revision = 'b07144688fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asm_number', sa.String(length=20), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('asm_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_repair_order_asm_id', 'asm', ['asm_id'], ['id'])

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_column('tech_number')

    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asm_id')
        batch_op.drop_column('service_description')

    op.drop_table('asm')
    # ### end Alembic commands ###
