"""Revert to single-user architecture

Revision ID: 9c3caacc91e0
Revises: 
Create Date: 2025-11-09 03:14:22.452043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3caacc91e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('labor_gross', sa.Float(), nullable=False),
    sa.Column('parts_gross', sa.Float(), nullable=False),
    sa.Column('other_gross', sa.Float(), nullable=True),
    sa.Column('total_gross', sa.Float(), nullable=False),
    sa.Column('expected_frh', sa.Float(), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starting_rate', sa.Float(), nullable=False),
    sa.Column('peak_hours', sa.Float(), nullable=False),
    sa.Column('escalator_percent', sa.Float(), nullable=False),
    sa.Column('return_normal_hours', sa.Float(), nullable=False),
    sa.Column('discount_start_hours', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('financial_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_labor_rate', sa.Float(), nullable=True),
    sa.Column('parts_to_labor_ratio', sa.Float(), nullable=True),
    sa.Column('labor_margin', sa.Float(), nullable=True),
    sa.Column('parts_margin', sa.Float(), nullable=True),
    sa.Column('other_ro_gross', sa.Float(), nullable=True),
    sa.Column('unapplied_time_cost', sa.Float(), nullable=True),
    sa.Column('parts_inventory_adjust', sa.Float(), nullable=True),
    sa.Column('parts_allowance', sa.Float(), nullable=True),
    sa.Column('purchase_discounts', sa.Float(), nullable=True),
    sa.Column('wholesale_gross', sa.Float(), nullable=True),
    sa.Column('parts_retail_gross', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('labor_grid_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('effective_rate', sa.Float(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['labor_grid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tech_level', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('daily_production_objective', sa.Float(), nullable=True),
    sa.Column('dpo_calculation_mode', sa.String(length=20), nullable=False),
    sa.Column('hist_frh_total', sa.Float(), nullable=True),
    sa.Column('hist_days_in_period', sa.Integer(), nullable=True),
    sa.Column('hist_training_days', sa.Integer(), nullable=True),
    sa.Column('hist_vacation_days', sa.Integer(), nullable=True),
    sa.Column('expected_lift_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_objective_memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('previous_objective', sa.Float(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('ro_number', sa.String(length=50), nullable=True),
    sa.Column('line_item', sa.String(length=10), nullable=True),
    sa.Column('flat_rate_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_log')
    op.drop_table('schedule_entry')
    op.drop_table('production_objective_memo')
    op.drop_table('team_schedule')
    op.drop_table('team_member')
    op.drop_table('labor_grid_rate')
    op.drop_table('financial_inputs')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('labor_grid')
    op.drop_table('financial_forecast')
    # ### end Alembic commands ###
