"""Revert to single-user architecture

Revision ID: 9c3caacc91e0
Revises: 
Create Date: 2025-11-09 03:14:22.452043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3caacc91e0'
down_revision = 'b81fac1fba23'
branch_labels = None
depends_on = None


def upgrade():
   pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###
