"""add unique constraint to roles

Revision ID: b06bd82ccd3e
Revises: 66e9d9594060
Create Date: 2026-02-15 18:26:48.739866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06bd82ccd3e'
down_revision = '66e9d9594060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_role_name_store', ['name', 'store_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_name_store', type_='unique')

    # ### end Alembic commands ###
