"""Create organizational groups

Revision ID: ce6ed3cc1e8a
Revises: 52c97fb4ecad
Create Date: 2026-08-01 11:05:01.304378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6ed3cc1e8a'
down_revision = '52c97fb4ecad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizational_groups',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('group_type', sa.Enum('market', 'region', 'district', 'division', 'platform', 'brand_group', 'ownership_group', 'operating_cluster', 'custom', name='organizational_group_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'retired', name='organizational_group_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('organizational_group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_organizational_groups_effective_period_valid')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_organizational_groups_name_required')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_organizational_groups_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organizational_group_id', name=op.f('pk_organizational_groups')),
    sa.UniqueConstraint('enterprise_id', 'code', name='uq_organizational_groups_enterprise_code'),
    sa.UniqueConstraint('enterprise_id', 'organizational_group_id', name='uq_organizational_groups_tenant_identity')
    )
    with op.batch_alter_table('organizational_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizational_groups_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_organizational_groups_enterprise_status', ['enterprise_id', 'status'], unique=False)
        batch_op.create_index('ix_organizational_groups_enterprise_type', ['enterprise_id', 'group_type'], unique=False)

    op.create_table('organizational_group_hierarchies',
    sa.Column('parent_group_id', sa.Uuid(), nullable=False),
    sa.Column('child_group_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('organizational_group_hierarchy_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_organizational_group_hierarchies_effective_period_valid')),
    sa.CheckConstraint('parent_group_id <> child_group_id', name=op.f('ck_organizational_group_hierarchies_parent_child_different')),
    sa.ForeignKeyConstraint(['enterprise_id', 'child_group_id'], ['organizational_groups.enterprise_id', 'organizational_groups.organizational_group_id'], name='fk_organizational_group_hierarchies_child_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'parent_group_id'], ['organizational_groups.enterprise_id', 'organizational_groups.organizational_group_id'], name='fk_organizational_group_hierarchies_parent_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_organizational_group_hierarchies_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organizational_group_hierarchy_id', name=op.f('pk_organizational_group_hierarchies')),
    sa.UniqueConstraint('enterprise_id', 'parent_group_id', 'child_group_id', 'effective_from', name='uq_organizational_group_hierarchies_effective_relationship')
    )
    with op.batch_alter_table('organizational_group_hierarchies', schema=None) as batch_op:
        batch_op.create_index('ix_organizational_group_hierarchies_child', ['enterprise_id', 'child_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizational_group_hierarchies_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_organizational_group_hierarchies_parent', ['enterprise_id', 'parent_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('organizational_group_hierarchies', schema=None) as batch_op:
        batch_op.drop_index('ix_organizational_group_hierarchies_parent')
        batch_op.drop_index(batch_op.f('ix_organizational_group_hierarchies_enterprise_id'))
        batch_op.drop_index('ix_organizational_group_hierarchies_child')

    op.drop_table('organizational_group_hierarchies')
    with op.batch_alter_table('organizational_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_organizational_groups_enterprise_type')
        batch_op.drop_index('ix_organizational_groups_enterprise_status')
        batch_op.drop_index(batch_op.f('ix_organizational_groups_enterprise_id'))

    op.drop_table('organizational_groups')
    # ### end Alembic commands ###
