"""Create roles

Revision ID: d05035d48cf1
Revises: fb35c323de14
Create Date: 2026-08-02 08:46:49.134329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05035d48cf1'
down_revision = 'fb35c323de14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'retired', name='role_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_roles_effective_period_valid')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_roles_name_required')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_roles_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('enterprise_id', 'code', name='uq_roles_enterprise_code'),
    sa.UniqueConstraint('enterprise_id', 'role_id', name='uq_roles_tenant_identity')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_roles_enterprise_name', ['enterprise_id', 'name'], unique=False)
        batch_op.create_index('ix_roles_enterprise_status', ['enterprise_id', 'status'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_enterprise_status')
        batch_op.drop_index('ix_roles_enterprise_name')
        batch_op.drop_index(batch_op.f('ix_roles_enterprise_id'))

    op.drop_table('roles')
    # ### end Alembic commands ###
