"""make team name unique per store

Revision ID: e15234e7efd9
Revises: 8eb8d4f1019d
Create Date: 2026-02-15 22:28:14.862193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15234e7efd9'
down_revision = '8eb8d4f1019d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team') as batch_op:
        batch_op.drop_constraint('team_name_key', type_='unique')
        batch_op.create_unique_constraint(
            'uq_team_store_name',
            ['store_id', 'name']
        )
        batch_op.create_index('ix_team_store_id', ['store_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_store_name', type_='unique')
        batch_op.drop_index('ix_team_store_id')

    # ### end Alembic commands ###
