"""sync managedstore fields

Revision ID: e911fa0caf85
Revises: 1819488dcf06
Create Date: 2026-02-15 20:11:00.102971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e911fa0caf85'
down_revision = '1819488dcf06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.drop_column('tier')
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
