"""fix named foreign keys

Revision ID: ea3fb583ddf7
Revises: 4c4b809e2b3b
Create Date: 2026-03-29 19:04:49.022536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3fb583ddf7'
down_revision = '4c4b809e2b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_action_store_time', ['store_id', 'timestamp'], unique=False)
        batch_op.create_foreign_key('fk_actionhistory_store', 'managed_store', ['store_id'], ['id'])

    with op.batch_alter_table('decision_weights', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_weights_store_id', ['store_id'], unique=False)
        batch_op.create_foreign_key('fk_weights_store', 'managed_store', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_weights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_weights_store', type_='foreignkey')
        batch_op.drop_index('ix_weights_store_id')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_actionhistory_store', type_='foreignkey')
        batch_op.drop_index('ix_action_store_time')
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
