"""Create role capability assignments

Revision ID: f93414eca218
Revises: 4f6ffabb9d08
Create Date: 2026-08-02 09:13:31.852054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93414eca218'
down_revision = '4f6ffabb9d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_capability_assignments',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('role_capability_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_role_capability_assignments_effective_period_valid')),
    sa.ForeignKeyConstraint(['enterprise_id', 'capability_id'], ['capabilities.enterprise_id', 'capabilities.capability_id'], name='fk_role_capability_assignments_capability', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'role_id'], ['roles.enterprise_id', 'roles.role_id'], name='fk_role_capability_assignments_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_role_capability_assignments_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_capability_id', name=op.f('pk_role_capability_assignments')),
    sa.UniqueConstraint('enterprise_id', 'role_capability_id', name='uq_role_capability_assignments_tenant_identity'),
    sa.UniqueConstraint('enterprise_id', 'role_id', 'capability_id', 'effective_from', name='uq_role_capability_assignments_effective_grant')
    )
    with op.batch_alter_table('role_capability_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_role_capability_assignments_capability', ['enterprise_id', 'capability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_capability_assignments_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_role_capability_assignments_role', ['enterprise_id', 'role_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('role_capability_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_role_capability_assignments_role')
        batch_op.drop_index(batch_op.f('ix_role_capability_assignments_enterprise_id'))
        batch_op.drop_index('ix_role_capability_assignments_capability')

    op.drop_table('role_capability_assignments')
    # ### end Alembic commands ###
