"""Create employee assignments

Revision ID: fb35c323de14
Revises: 42c60d2e3cf2
Create Date: 2026-08-02 08:29:29.778555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb35c323de14'
down_revision = '42c60d2e3cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_assignments',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'leave', 'completed', 'cancelled', name='employee_assignment_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('employee_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_employee_assignments_effective_period_valid')),
    sa.ForeignKeyConstraint(['enterprise_id', 'employee_id'], ['employees.enterprise_id', 'employees.employee_id'], name='fk_employee_assignments_employee', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id', 'position_id'], ['positions.enterprise_id', 'positions.position_id'], name='fk_employee_assignments_position', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], name=op.f('fk_employee_assignments_enterprise_id_enterprises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('employee_assignment_id', name=op.f('pk_employee_assignments')),
    sa.UniqueConstraint('enterprise_id', 'employee_assignment_id', name='uq_employee_assignments_tenant_identity'),
    sa.UniqueConstraint('enterprise_id', 'employee_id', 'position_id', 'effective_from', name='uq_employee_assignments_employee_position_start')
    )
    with op.batch_alter_table('employee_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_employee_assignments_employee_status', ['enterprise_id', 'employee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_assignments_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index('ix_employee_assignments_position_status', ['enterprise_id', 'position_id', 'status'], unique=False)
        batch_op.create_index('uq_employee_assignments_current_primary', ['enterprise_id', 'employee_id'], unique=True, sqlite_where=sa.text("is_primary = 1 AND effective_to IS NULL AND status IN ('pending', 'active', 'leave')"), postgresql_where=sa.text("is_primary = true AND effective_to IS NULL AND status IN ('pending', 'active', 'leave')"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('employee_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_employee_assignments_current_primary', sqlite_where=sa.text("is_primary = 1 AND effective_to IS NULL AND status IN ('pending', 'active', 'leave')"), postgresql_where=sa.text("is_primary = true AND effective_to IS NULL AND status IN ('pending', 'active', 'leave')"))
        batch_op.drop_index('ix_employee_assignments_position_status')
        batch_op.drop_index(batch_op.f('ix_employee_assignments_enterprise_id'))
        batch_op.drop_index('ix_employee_assignments_employee_status')

    op.drop_table('employee_assignments')
    # ### end Alembic commands ###
