"""Add audit timestamps for routesheet and tech hours

Revision ID: fcae7fcaecca
Revises: 8d80f5b4b871
Create Date: 2026-03-15 09:55:12.139251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcae7fcaecca'
down_revision = '8d80f5b4b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routesheet_audit_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tech_hours_audit_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_store', schema=None) as batch_op:
        batch_op.drop_column('tech_hours_audit_timestamp')
        batch_op.drop_column('routesheet_audit_timestamp')

    # ### end Alembic commands ###
